import { useState } from "react";

const severityColors = {
  low: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
  medium: "bg-amber-500/10 text-amber-400 border-amber-500/20",
  high: "bg-rose-500/10 text-rose-400 border-rose-500/20",
};

const tabs = [
  { id: "overview", label: "Overview" },
  { id: "technical", label: "Technical Q&A" },
  { id: "behavioral", label: "Behavioral Q&A" },
  { id: "gaps", label: "Skill Gaps" },
  { id: "plan", label: "Prep Plan" },
];

const ReportView = ({ report, onBack, user, onLogout }) => {
  const [activeTab, setActiveTab] = useState("overview");

  const matchScore = report.matchScore || 0;

  const getScoreColor = (score) => {
    if (score >= 80) return { text: "text-emerald-400", bg: "bg-emerald-400", ring: "ring-emerald-400/20" };
    if (score >= 60) return { text: "text-amber-400", bg: "bg-amber-400", ring: "ring-amber-400/20" };
    return { text: "text-rose-400", bg: "bg-rose-400", ring: "ring-rose-400/20" };
  };

  const scoreColor = getScoreColor(matchScore);

  return (
    <div className="min-h-screen bg-[#171717] text-white overflow-auto">
      {/* Ambient glow */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden">
        <div className="absolute -top-40 -left-40 w-96 h-96 bg-amber-500/10 rounded-full blur-[128px]" />
        <div className="absolute -bottom-40 -right-40 w-96 h-96 bg-orange-500/8 rounded-full blur-[128px]" />
      </div>

      {/* Navbar */}
      <nav className="relative z-10 flex items-center justify-between px-6 md:px-12 py-4 border-b border-white/5">
        <div className="flex items-center gap-3">
          <button onClick={onBack} className="flex items-center gap-2 text-gray-400 hover:text-white transition-colors">
            <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" viewBox="0 0 20 20" fill="currentColor">
              <path fillRule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clipRule="evenodd" />
            </svg>
            <span className="text-sm font-medium">New Report</span>
          </button>
          <div className="w-px h-6 bg-white/10 ml-2" />
          <div className="flex items-center gap-2 ml-2">
            <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-amber-400 to-orange-500 flex items-center justify-center">
              <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4 text-gray-900" viewBox="0 0 24 24" fill="currentColor">
                <path d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
              </svg>
            </div>
            <span className="text-lg font-bold">
              Interview<span className="text-amber-400">AI</span>
            </span>
          </div>
        </div>
        <div className="flex items-center gap-4">
          <div className="hidden sm:flex items-center gap-2 px-3 py-1.5 rounded-full bg-white/5 border border-white/10">
            <div className="w-6 h-6 rounded-full bg-gradient-to-br from-amber-400 to-orange-500 flex items-center justify-center text-xs font-bold text-gray-900">
              {user?.username?.charAt(0).toUpperCase()}
            </div>
            <span className="text-sm text-gray-300">{user?.username}</span>
          </div>
          <button onClick={onLogout} className="px-4 py-2 text-sm font-medium rounded-xl border border-white/10 text-gray-300 hover:bg-white/5 hover:text-white transition-all duration-200">
            Logout
          </button>
        </div>
      </nav>

      <div className="relative z-10 max-w-5xl mx-auto px-4 py-8">
        {/* Report Header */}
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6 mb-8">
          <div>
            <h1 className="text-2xl md:text-3xl font-bold mb-1">{report.title || "Interview Report"}</h1>
            <p className="text-gray-400 text-sm">Generated by AI • Review and prepare</p>
          </div>
          {/* Score Badge */}
          <div className={`flex items-center gap-4 px-6 py-4 rounded-2xl border bg-white/[0.03] border-white/10`}>
            <div className={`relative w-16 h-16 rounded-full flex items-center justify-center ring-4 ${scoreColor.ring}`}>
              <div className={`absolute inset-1 rounded-full border-4 ${scoreColor.text} border-current opacity-20`} />
              <span className={`text-2xl font-extrabold ${scoreColor.text}`}>{matchScore}</span>
            </div>
            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wider font-medium">Match Score</p>
              <p className={`text-sm font-semibold ${scoreColor.text}`}>
                {matchScore >= 80 ? "Excellent Match" : matchScore >= 60 ? "Good Match" : "Needs Work"}
              </p>
            </div>
          </div>
        </div>

        {/* Tab Navigation */}
        <div className="flex gap-1 mb-8 p-1 rounded-2xl bg-white/[0.03] border border-white/5 overflow-x-auto">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex-1 min-w-[100px] px-4 py-2.5 rounded-xl text-sm font-medium transition-all duration-200 whitespace-nowrap ${
                activeTab === tab.id
                  ? "bg-gradient-to-r from-amber-400 to-orange-500 text-gray-900"
                  : "text-gray-400 hover:text-white hover:bg-white/5"
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* Tab Content */}
        <div className="animate-[fadeIn_0.3s_ease-in-out]">
          {/* Overview Tab */}
          {activeTab === "overview" && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Stats */}
              <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6">
                <h3 className="text-sm font-medium text-gray-500 uppercase tracking-wider mb-4">Quick Stats</h3>
                <div className="space-y-4">
                  <div className="flex justify-between items-center">
                    <span className="text-gray-400 text-sm">Technical Questions</span>
                    <span className="text-white font-semibold">{report.technicalQuestions?.length || 0}</span>
                  </div>
                  <div className="w-full h-px bg-white/5" />
                  <div className="flex justify-between items-center">
                    <span className="text-gray-400 text-sm">Behavioral Questions</span>
                    <span className="text-white font-semibold">{report.behavioralQuestions?.length || 0}</span>
                  </div>
                  <div className="w-full h-px bg-white/5" />
                  <div className="flex justify-between items-center">
                    <span className="text-gray-400 text-sm">Skill Gaps Identified</span>
                    <span className="text-white font-semibold">{report.skillGaps?.length || 0}</span>
                  </div>
                  <div className="w-full h-px bg-white/5" />
                  <div className="flex justify-between items-center">
                    <span className="text-gray-400 text-sm">Preparation Days</span>
                    <span className="text-white font-semibold">{report.preparationPlan?.length || 0}</span>
                  </div>
                </div>
              </div>

              {/* Skill Gaps Summary */}
              <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6">
                <h3 className="text-sm font-medium text-gray-500 uppercase tracking-wider mb-4">Skill Gaps Overview</h3>
                {report.skillGaps?.length > 0 ? (
                  <div className="space-y-3">
                    {report.skillGaps.map((gap, i) => (
                      <div key={i} className="flex items-center justify-between">
                        <span className="text-gray-300 text-sm">{gap.skill}</span>
                        <span className={`px-2.5 py-0.5 rounded-full text-xs font-medium border ${severityColors[gap.severity]}`}>
                          {gap.severity}
                        </span>
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="text-gray-500 text-sm">No skill gaps identified</p>
                )}
              </div>
            </div>
          )}

          {/* Technical Questions Tab */}
          {activeTab === "technical" && (
            <div className="space-y-4">
              {report.technicalQuestions?.map((q, i) => (
                <QuestionCard key={i} index={i + 1} question={q} accentColor="blue" />
              ))}
              {(!report.technicalQuestions || report.technicalQuestions.length === 0) && (
                <EmptyState text="No technical questions generated" />
              )}
            </div>
          )}

          {/* Behavioral Questions Tab */}
          {activeTab === "behavioral" && (
            <div className="space-y-4">
              {report.behavioralQuestions?.map((q, i) => (
                <QuestionCard key={i} index={i + 1} question={q} accentColor="purple" />
              ))}
              {(!report.behavioralQuestions || report.behavioralQuestions.length === 0) && (
                <EmptyState text="No behavioral questions generated" />
              )}
            </div>
          )}

          {/* Skill Gaps Tab */}
          {activeTab === "gaps" && (
            <div className="space-y-4">
              {report.skillGaps?.map((gap, i) => (
                <div key={i} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5 flex items-start gap-4">
                  <div className={`mt-0.5 w-8 h-8 shrink-0 rounded-xl flex items-center justify-center ${
                    gap.severity === "high" ? "bg-rose-500/10" : gap.severity === "medium" ? "bg-amber-500/10" : "bg-emerald-500/10"
                  }`}>
                    <svg xmlns="http://www.w3.org/2000/svg" className={`w-4 h-4 ${
                      gap.severity === "high" ? "text-rose-400" : gap.severity === "medium" ? "text-amber-400" : "text-emerald-400"
                    }`} viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                    </svg>
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center justify-between">
                      <h3 className="font-semibold text-white">{gap.skill}</h3>
                      <span className={`px-3 py-1 rounded-full text-xs font-medium border ${severityColors[gap.severity]}`}>
                        {gap.severity} severity
                      </span>
                    </div>
                  </div>
                </div>
              ))}
              {(!report.skillGaps || report.skillGaps.length === 0) && (
                <EmptyState text="No skill gaps identified" />
              )}
            </div>
          )}

          {/* Preparation Plan Tab */}
          {activeTab === "plan" && (
            <div className="space-y-4">
              {report.preparationPlan?.map((day, i) => (
                <div key={i} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-amber-400/20 to-orange-500/20 border border-amber-400/20 flex items-center justify-center">
                      <span className="text-amber-400 font-bold text-sm">{day.day}</span>
                    </div>
                    <div>
                      <p className="text-xs text-gray-500 uppercase tracking-wider">Day {day.day}</p>
                      <h3 className="font-semibold text-white">{day.focus}</h3>
                    </div>
                  </div>
                  <ul className="space-y-2 ml-1">
                    {day.tasks?.map((task, j) => (
                      <li key={j} className="flex items-start gap-3 text-sm text-gray-300">
                        <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-amber-400/60 shrink-0" />
                        <span className="leading-relaxed">{task}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
              {(!report.preparationPlan || report.preparationPlan.length === 0) && (
                <EmptyState text="No preparation plan generated" />
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

/* ---- Sub-Components ---- */

const QuestionCard = ({ index, question, accentColor }) => {
  const [isOpen, setIsOpen] = useState(false);

  const colors = {
    blue: { badge: "bg-blue-500/10 text-blue-400 border-blue-500/20", dot: "bg-blue-400" },
    purple: { badge: "bg-purple-500/10 text-purple-400 border-purple-500/20", dot: "bg-purple-400" },
  };
  const c = colors[accentColor] || colors.blue;

  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.03] overflow-hidden transition-all duration-200">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex items-start gap-4 p-5 text-left hover:bg-white/[0.02] transition-colors"
      >
        <span className={`shrink-0 mt-0.5 px-2.5 py-0.5 rounded-full text-xs font-semibold border ${c.badge}`}>
          Q{index}
        </span>
        <span className="flex-1 font-medium text-white leading-relaxed">{question.question}</span>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          className={`w-5 h-5 text-gray-400 shrink-0 mt-0.5 transition-transform duration-200 ${isOpen ? "rotate-180" : ""}`}
          viewBox="0 0 20 20"
          fill="currentColor"
        >
          <path fillRule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clipRule="evenodd" />
        </svg>
      </button>

      {isOpen && (
        <div className="px-5 pb-5 border-t border-white/5">
          <div className="mt-4 space-y-4">
            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wider font-medium mb-1.5">Interviewer's Intention</p>
              <p className="text-sm text-gray-300 leading-relaxed">{question.intention}</p>
            </div>
            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wider font-medium mb-1.5">How to Answer</p>
              <p className="text-sm text-gray-300 leading-relaxed">{question.answer}</p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

const EmptyState = ({ text }) => (
  <div className="rounded-2xl border border-white/5 bg-white/[0.02] p-12 text-center">
    <svg xmlns="http://www.w3.org/2000/svg" className="w-10 h-10 text-gray-600 mx-auto mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4" />
    </svg>
    <p className="text-gray-500 text-sm">{text}</p>
  </div>
);

export default ReportView;
